/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.testes;

public class Item extends javax.swing.JFrame {

    /**
     * Creates new form BoxFilmes
     */
    public Item() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        janela = new javax.swing.JPanel();
        pnlBox = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        btnHeaderArrow = new javax.swing.JButton();
        lblHeaderTitle = new javax.swing.JLabel();
        scpItems = new javax.swing.JScrollPane();
        pnlItems = new javax.swing.JPanel();
        pnlItem = new javax.swing.JPanel();
        pnlItemDivisor = new javax.swing.JPanel();
        lblItemImagem = new javax.swing.JLabel();
        lblItemDescricao = new javax.swing.JLabel();
        lblItemValor = new javax.swing.JLabel();
        lblItemNome = new javax.swing.JLabel();
        lblItemTitDiaria = new javax.swing.JLabel();
        btnItemMais = new javax.swing.JButton();
        btnItemAdicionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        janela.setAlignmentX(0.0F);
        janela.setPreferredSize(new java.awt.Dimension(900, 600));
        janela.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBox.setPreferredSize(new java.awt.Dimension(900, 320));
        pnlBox.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setBackground(new java.awt.Color(239, 239, 239));
        pnlHeader.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHeaderArrow.setText("v");
        btnHeaderArrow.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnHeaderArrow.setMaximumSize(new java.awt.Dimension(60, 60));
        btnHeaderArrow.setPreferredSize(new java.awt.Dimension(60, 60));
        pnlHeader.add(btnHeaderArrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 30, 30));

        lblHeaderTitle.setText("Lançamentos");
        pnlHeader.add(lblHeaderTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 11, -1, -1));

        pnlBox.add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 39));

        scpItems.setBackground(new java.awt.Color(239, 239, 239));
        scpItems.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        scpItems.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        pnlItems.setBackground(new java.awt.Color(243, 243, 243));
        pnlItems.setPreferredSize(new java.awt.Dimension(240, 332));
        pnlItems.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlItem.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlItem.setPreferredSize(new java.awt.Dimension(210, 300));
        pnlItem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlItemDivisor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlItemDivisor.setPreferredSize(new java.awt.Dimension(212, 2));

        javax.swing.GroupLayout pnlItemDivisorLayout = new javax.swing.GroupLayout(pnlItemDivisor);
        pnlItemDivisor.setLayout(pnlItemDivisorLayout);
        pnlItemDivisorLayout.setHorizontalGroup(
            pnlItemDivisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlItemDivisorLayout.setVerticalGroup(
            pnlItemDivisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlItem.add(pnlItemDivisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 126, 208, -1));

        lblItemImagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItemImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resources/video-camera.png"))); // NOI18N
        pnlItem.add(lblItemImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 130));

        lblItemDescricao.setText("blá blá");
        lblItemDescricao.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblItemDescricao.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblItemDescricao.setPreferredSize(new java.awt.Dimension(31, 75));
        lblItemDescricao.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        pnlItem.add(lblItemDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 157, 198, 75));

        lblItemValor.setText("R$ 4,50");
        pnlItem.add(lblItemValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 235, -1, 20));

        lblItemNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblItemNome.setText("Nome do Filme");
        pnlItem.add(lblItemNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 135, -1, -1));

        lblItemTitDiaria.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblItemTitDiaria.setText("Diária:");
        pnlItem.add(lblItemTitDiaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 235, -1, 20));

        btnItemMais.setText("Mais");
        btnItemMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemMaisActionPerformed(evt);
            }
        });
        pnlItem.add(btnItemMais, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 265, -1, -1));

        btnItemAdicionar.setText("Adicionar");
        pnlItem.add(btnItemAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 265, -1, -1));

        pnlItems.add(pnlItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        scpItems.setViewportView(pnlItems);

        pnlBox.add(scpItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 38, 900, 330));

        janela.add(pnlBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(janela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(janela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnItemMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemMaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnItemMaisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Item().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHeaderArrow;
    private javax.swing.JButton btnItemAdicionar;
    private javax.swing.JButton btnItemMais;
    private javax.swing.JPanel janela;
    private javax.swing.JLabel lblHeaderTitle;
    private javax.swing.JLabel lblItemDescricao;
    private javax.swing.JLabel lblItemImagem;
    private javax.swing.JLabel lblItemNome;
    private javax.swing.JLabel lblItemTitDiaria;
    private javax.swing.JLabel lblItemValor;
    private javax.swing.JPanel pnlBox;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlItem;
    private javax.swing.JPanel pnlItemDivisor;
    private javax.swing.JPanel pnlItems;
    private javax.swing.JScrollPane scpItems;
    // End of variables declaration//GEN-END:variables
}
