/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import model.FilmeINF;

public class ListaFilmesFRM extends javax.swing.JFrame {

    public PrincipalFRM principalFRM = null;

    /**
     * Creates new form ListaFilmesFRM
     */
    public ListaFilmesFRM() {
        initComponents();

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                super.windowClosing(e); //To change body of generated methods, choose Tools | Templates.

                ListaFilmesFRM.this.dispose();

                /*int res = JOptionPane.showConfirmDialog(CadastroFRM.this, "Are you sure you want to close?", "Close?", JOptionPane.YES_NO_OPTION);
                if ( res == 0 ) {
                    CadastroFRM.this.dispose();
                }*/
            }

        });

        javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel) jtbFilmes.getModel();

        double vlrTotal = 0;
        Object[] dados = null;
        FilmeINF filme = null;

        for (int i = 0; i < PrincipalFRM.filmesEscolhidos.size(); i++) {
            filme = PrincipalFRM.filmesEscolhidos.get(i);
            dados = new Object[2];
            dados[0] = filme.getNome();
            dados[1] = new DecimalFormat("'R$' #,###,##0.00").format(filme.getValorAluguel().doubleValue());

            vlrTotal += Double.parseDouble(filme.getValorAluguel().toString());

            dtm.addRow(dados);
        }

        lblVlrTotal.setText(new DecimalFormat("'R$' #,###,##0.00").format(vlrTotal));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbFilmes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblVlrTotal = new javax.swing.JLabel();
        btnContinuarEscolhendo = new javax.swing.JButton();
        btnLimparLista = new javax.swing.JButton();
        btnFinalizarAluguel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Minha lista de filmes");
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(650, 425));
        setResizable(false);
        setSize(new java.awt.Dimension(650, 425));

        jtbFilmes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome do filme", "Valor Aluguel"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtbFilmes);
        if (jtbFilmes.getColumnModel().getColumnCount() > 0) {
            jtbFilmes.getColumnModel().getColumn(0).setPreferredWidth(100);
            jtbFilmes.getColumnModel().getColumn(1).setPreferredWidth(100);
            jtbFilmes.getColumnModel().getColumn(1).setMaxWidth(100);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Total:");

        lblVlrTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblVlrTotal.setText("R$ 0,00");

        btnContinuarEscolhendo.setText("Continuar escolhendo");
        btnContinuarEscolhendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarEscolhendoActionPerformed(evt);
            }
        });

        btnLimparLista.setText("Limpar lista");
        btnLimparLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparListaActionPerformed(evt);
            }
        });

        btnFinalizarAluguel.setText("Finalizar aluguel");
        btnFinalizarAluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarAluguelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(lblVlrTotal))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnLimparLista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnContinuarEscolhendo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFinalizarAluguel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblVlrTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimparLista)
                    .addComponent(btnContinuarEscolhendo)
                    .addComponent(btnFinalizarAluguel))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarEscolhendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarEscolhendoActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnContinuarEscolhendoActionPerformed

    private void btnLimparListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparListaActionPerformed
        javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel) jtbFilmes.getModel();

        dtm.getDataVector().removeAllElements();
        dtm.fireTableDataChanged();

        principalFRM.clearFilmesEscolhidos();
    }//GEN-LAST:event_btnLimparListaActionPerformed

    private void btnFinalizarAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarAluguelActionPerformed
        if (validaFilmes() && validaUsuario()) {
            JOptionPane.showMessageDialog(this, "Aluguel realizado com sucesso.", "Informação", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnFinalizarAluguelActionPerformed

    private boolean validaFilmes() {
        if (PrincipalFRM.filmesEscolhidos.size() == 0) {
            JOptionPane.showMessageDialog(this, "Não foi possível finalizar o aluguel, pois nenhum filme foi adicionado à sua lista.", "Atenção", JOptionPane.WARNING_MESSAGE);
            return false;
        } else {
            return true;
        }
    }

    private boolean validaUsuario() {
        if (PrincipalFRM.usuarioLocflix.getNomeCompleto().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Não foi possível finalizar o aluguel. \n\n Para finalizar o aluguel, é necessário se cadastrar no sistema.", "Atenção", JOptionPane.WARNING_MESSAGE);
            return false;
        } else {
            return true;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaFilmesFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaFilmesFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaFilmesFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaFilmesFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaFilmesFRM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuarEscolhendo;
    private javax.swing.JButton btnFinalizarAluguel;
    private javax.swing.JButton btnLimparLista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbFilmes;
    private javax.swing.JLabel lblVlrTotal;
    // End of variables declaration//GEN-END:variables
}
